---
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lapidary
      POSTGRES_USER: lapidary
      POSTGRES_PASSWORD: lapidary

  lapidary:
    # replace username/repo:tag with your name and image details
    image: theasp/lapidary
    restart: always
    ports:
      - "8081:80"
    environment:
      HTTP__ADDRESS: 0.0.0.0
      HTTP__PORT: 80
      DB__HOSTNAME: db
      DB__PORT: 5432
      DB__USERNAME: lapidary
      DB__PASSWORD: lapidary
      DB__DATABASE: lapidary
      JWT__SECRET: "Change this string to something random, like a UUID"

      # Static users
      USERS__ADMIN__PASSWORD: "ChangeMe!"
      USERS__ADMIN__ROLE: admin
      # USERS__THEASP__PASSWORD: "letmein!"
      # USERS__THEASP__ROLE: admin

      # To use LDAP
      # AUTH__METHOD: ldap
      # LDAP__URL: ldaps://ldap.example.com
      # LDAP__BIND_DN: cn=readonly,dc=example,dc=com
      # LDAP__BIND_PASSWORD: "example"
      # LDAP__USER_BASE_DN: "ou=people,dc=example,dc=com"
      # LDAP__USER_FILTER: "(uid={{username}})"
      # LDAP__ROLE_MAPPINGS__ADMIN: cn=lapdiary-admin,ou=group,dc=example,dc=com
      # LDAP__USER_ATTR: uid
      # LDAP__GROUP_ATTR: memberOf
      # LDAP__RECONNECT: true
      # LDAP__TLS_VERIFY: true
    depends_on:
      - db

  fluentd:
    image: theasp/fluentd-plugins:pgjson
    restart: always
    ports:
      - "24225:24224"
      - "9881:9880"
    volumes:
      - "/srv/lapidary-fluentd/etc:/fluentd/etc"
      - "/srv/lapidary-fluentd/log:/fluentd/log"
      - "/srv/lapidary-fluentd/pos:/fluentd/pos"
      # If you want to log from systemd on localhost, you can use these
      # - /etc/machine-id:/etc/machine-id:ro
      # - /var/log:/var/log:ro
      # - /run/log/journal:/run/log/journal:ro
      # - /run/systemd/journal:/run/systemd/journal:ro
    depends_on:
      - db
