---
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lapidary
      POSTGRES_USER: lapidary
      POSTGRES_PASSWORD: lapidary

  lapidary:
    # replace username/repo:tag with your name and image details
    image: theasp/lapidary
    restart: always
    ports:
      - "48080:80"
    environment:
      HTTP__ADDRESS: 0.0.0.0
      HTTP__PORT: 80
      DB__HOSTNAME: db
      DB__PORT: 5432
      DB__USERNAME: lapidary
      DB__PASSWORD: lapidary
      DB__DATABASE: lapidary
      AUTH__ADMIN_USER: admin
      AUTH__ADMIN_PASSWORD: "ChangeMe!"
      JWT__SECRET: "Change this string to something random, like a UUUID"
    depends_on:
      - db

  fluentd:
    image: theasp/fluentd-plugins:pgjson
    restart: always
    ports:
      - "42442:24224"
      - "49880:9880"
    volumes:
      - "/srv/lapidary-fluentd/etc:/fluentd/etc"
      - "/srv/lapidary-fluentd/log:/fluentd/log"
      - "/srv/lapidary-fluentd/pos:/fluentd/pos"
      # If you want to log from systemd on localhost, you can use these
      # - /etc/machine-id:/etc/machine-id:ro
      # - /var/log:/var/log:ro
      # - /run/log/journal:/run/log/journal:ro
      # - /run/systemd/journal:/run/systemd/journal:ro
    depends_on:
      - db
