---
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: lapidary
      POSTGRES_USER: lapidary
      POSTGRES_PASSWORD: lapidary

  lapidary:
    # replace username/repo:tag with your name and image details
    image: theasp/lapidary
    restart: always
    ports:
      - "3011:80"
    environment:
      DB_HOST: db
      DB_USER: lapidary
      DB_PASSWORD: lapidary
      DB_NAME: lapidary
    depends_on:
      - db

  fluentd:
    image: theasp/fluentd-plugins:pgjson
    restart: always
    ports:
      - "24224:24224"
      - "9880:9880"
    volumes:
      - "/srv/lapidary-fluentd/etc:/fluentd/etc"
      - "/srv/lapidary-fluentd/log:/fluentd/log"
      - "/srv/lapidary-fluentd/pos:/fluentd/pos"
      # If you want to log from systemd on localhost, you can use these
      # - /etc/machine-id:/etc/machine-id:ro
      # - /var/log:/var/log:ro
      # - /run/log/journal:/run/log/journal:ro
      # - /run/systemd/journal:/run/systemd/journal:ro
    depends_on:
      - db
