---
version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: |
          docker image build -t theasp/lapidary:latest -f Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push theasp/lapidary:latest
workflows:
  version: 2
  build:
    jobs:
      - build
